@ECHO OFF
IF NOT pwd==%cd% (cd /d %~dp0) 
ECHO Setting global variables...

FOR %%A IN ("%~dp0.") DO SET "ROOTPATH=%%~dpA"
set "TOOLSPATH=C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools"
set "CMAKEPATH=C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE"
set "NINJAPATH=C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\Ninja"

@REM jos ei toimi testaa näitä 
@REM set "TOOLSPATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools"
@REM set "CMAKEPATH=C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE"
@REM set "NINJAPATH=C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\Ninja"

set "COMPILERPATH=cl.exe"

ECHO Done.
